language: generic 
sudo: required
services:
    - docker 

# # Build testing container
# before_install:
#     - docker build -t dynamisdevelopment/test-container -f .

# # Run Tests
# script:
#     - docker run -e CI=true dynamisdevelopment/test-container npm test -- --coverage


deploy: 
    provider: elasticbeanstalk 
    region: "eu-west-1"
    app: "shit-gifts-application"
    env: "ShitGiftsApplication-env" 
    bucket_name: "elasticbeanstalk-eu-west-1-997997896234"
    bucket_path: "shit-gifts-application"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY