version: "3"
services:
    client:
        stdin_open: true
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: shitgifts
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app
    api:
        stdin_open: true
        container_name: api
        build:
            context: ./api
            dockerfile: Dockerfile
        image: shitgifts
        ports:
            - "3001:3001"
        volumes:
            - ./api:/usr/src/app